# Generated by Django 5.2 on 2025-04-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Carros",
            new_name="Carro",
        ),
    ]
