# Generated by Django 5.2 on 2025-04-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_rename_carros_carro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="carro",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carro_marca",
                to="cars.marca",
            ),
        ),
    ]
