# Generated by Django 5.2 on 2025-04-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_marca_alter_carro_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="carro",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="carros/"),
        ),
    ]
