# Generated by Django 5.2 on 2025-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_carro_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantidade", models.IntegerField()),
                ("valor", models.FloatField()),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-data_entrada"],
            },
        ),
    ]
