# Generated by Django 5.2 on 2025-04-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_inventario"),
    ]

    operations = [
        migrations.AddField(
            model_name="carro",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
