# Generated by Django 5.2 on 2025-04-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_carro_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventario",
            options={"ordering": ["-data"]},
        ),
        migrations.RenameField(
            model_name="inventario",
            old_name="data_entrada",
            new_name="data",
        ),
    ]
